### ISSUE TITLE
Error on add, help ...

### ISSUE THREAD

**Issue by juangnzalez** [alphabetum/notes#3]
This is the error I get at the first start of the application:

MacB :: ~ » notes
home

0 notes.

Add a note:
  notes add
Usage information:
  notes help
MacB :: ~ 1 » notes help
Usage: _get_title <basename>
❌  Not found: help

Versions:

MacB :: ~ 1 » brew -v
Homebrew 1.3.2
Homebrew/homebrew-core (git revision d8de8; last commit 2017-09-06)

MacB :: ~ » zsh --version
zsh 5.3.1 (x86_64-apple-darwin16.3.0)

macos 10.12.6

thank you very much

**Comment by alphabetum** [comment]
Hi! It looks like this is due to an issue with the built-in version of Bash on macOS, which is version 3.2. `notes` uses some features from later versions of Bash, so it requires Bash 4.3 or later. Bash 4.4 is available to install with homebrew with `brew install bash`. Once Bash is updated it should work. I hope this helps!

**Comment by juangnzalez** [comment]
upps sorry i missed the requirements.
After the update all correct.
Forgive me for the time it took you to answer.
Thanks a lot, it's a great app.
